--- #YAML:1.0
name:               Module-Install-DiffCheck
version:            0.01
abstract:           Run diff commands looking for deployment problems
author:
    - Jay Hannah <jay@jays.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    inc::Module::Install:  0
    Test::More:           0
    Text::Diff::Parser:   0.1000
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
